version: '3.8'
services:
  db:
    image: postgres:16
    container_name: my_local_postgres_aa41
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: aa_41 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d aa_41"] 
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: