name: Python CI

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    - name: Set up Python 3.9
      uses: actions/setup-python@v5 
      with:
        python-version: '3.9'

    - name: Install Black
      run: |
        python -m pip install --upgrade pip # Upgrade pip
        pip install black # Install Black formatter

    - name: Run Black check
      run: black --check --diff .

  test:
    runs-on: ubuntu-latest
    needs: format 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests with pytest
      run: pytest